USE [master]
CREATE DATABASE [TestDB]
USE [TestDB]

CREATE TABLE [dbo].[AUTHENTICATIONS](
	[AUTHENTICATION_ID] [nvarchar](50) NOT NULL,
	[ACCOUNT] [nvarchar](26) NOT NULL,
	[PASSWORD] [nvarchar](30) NOT NULL,
	[EMAIL] [nvarchar](500) NOT NULL,
	[AUTHORIZATION_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[AUTHENTICATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AUTHORIZATIONS]    Script Date: 16/09/2024 13:35:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AUTHORIZATIONS](
	[AUTHORIZATION_ID] [int] NOT NULL,
	[AUTHORIZATION_NAME] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[AUTHORIZATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERS]    Script Date: 16/09/2024 13:35:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS](
	[USER_ID] [nvarchar](50) NOT NULL,
	[AUTHENTICATION_ID] [nvarchar](50) NOT NULL,
	[USER_NAME] [nvarchar](50) NOT NULL,
	[DISPLAY_FIRST_NAME] [nvarchar](50) NULL,
	[DISPLAY_LAST_NAME] [nvarchar](50) NULL,
	[GENDER] [bit] NOT NULL,
	[BIRTH_DATE] [date] NOT NULL,
	[PHONE_NUMBER] [nvarchar](50) NULL,
	[ADDRESS] [nvarchar](max) NULL,
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC,
	[AUTHENTICATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[AUTHENTICATIONS] ([AUTHENTICATION_ID], [ACCOUNT], [PASSWORD], [EMAIL], [AUTHORIZATION_ID]) VALUES (N'admin0', N'qthiendev', N'qthiendev', N'decseize4work@gmail.com', 0)
GO
INSERT [dbo].[AUTHENTICATIONS] ([AUTHENTICATION_ID], [ACCOUNT], [PASSWORD], [EMAIL], [AUTHORIZATION_ID]) VALUES (N'esp1', N'testuser_esp', N'testuser', N'test_esp@gmail.com', 2)
GO
INSERT [dbo].[AUTHENTICATIONS] ([AUTHENTICATION_ID], [ACCOUNT], [PASSWORD], [EMAIL], [AUTHORIZATION_ID]) VALUES (N'student0', N'testuser_student', N'testuser', N'test_stu@gmail.com', 1)
GO
INSERT [dbo].[AUTHORIZATIONS] ([AUTHORIZATION_ID], [AUTHORIZATION_NAME]) VALUES (0, N'admin')
GO
INSERT [dbo].[AUTHORIZATIONS] ([AUTHORIZATION_ID], [AUTHORIZATION_NAME]) VALUES (1, N'student')
GO
INSERT [dbo].[AUTHORIZATIONS] ([AUTHORIZATION_ID], [AUTHORIZATION_NAME]) VALUES (2, N'education service')
GO
INSERT [dbo].[USERS] ([USER_ID], [AUTHENTICATION_ID], [USER_NAME], [DISPLAY_FIRST_NAME], [DISPLAY_LAST_NAME], [GENDER], [BIRTH_DATE], [PHONE_NUMBER], [ADDRESS]) VALUES (N'uesr0', N'admin0', N'qthiendev', N'Thiện', N'Trịnh Quý', 1, CAST(N'2003-12-16' AS Date), N'0395075100', N'Cẩm Lệ, Đà Nẵng, Việt Nam')
GO
INSERT [dbo].[USERS] ([USER_ID], [AUTHENTICATION_ID], [USER_NAME], [DISPLAY_FIRST_NAME], [DISPLAY_LAST_NAME], [GENDER], [BIRTH_DATE], [PHONE_NUMBER], [ADDRESS]) VALUES (N'user1', N'student0', N'testStudent', N'Student', N'I''m', 0, CAST(N'2001-09-11' AS Date), N'0932917111', N'Thanh Khê')
GO
INSERT [dbo].[USERS] ([USER_ID], [AUTHENTICATION_ID], [USER_NAME], [DISPLAY_FIRST_NAME], [DISPLAY_LAST_NAME], [GENDER], [BIRTH_DATE], [PHONE_NUMBER], [ADDRESS]) VALUES (N'user2', N'esp1', N'testESP', N'Provider', N'Education Service', 1, CAST(N'2003-12-24' AS Date), N'0998811133', N'Sơn Trà')
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__AUTHENTI__161CF72427B13131]    Script Date: 16/09/2024 13:35:36 ******/
ALTER TABLE [dbo].[AUTHENTICATIONS] ADD UNIQUE NONCLUSTERED 
(
	[EMAIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__AUTHENTI__A7301CB7F0E86D8F]    Script Date: 16/09/2024 13:35:36 ******/
ALTER TABLE [dbo].[AUTHENTICATIONS] ADD UNIQUE NONCLUSTERED 
(
	[ACCOUNT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__USERS__0CC04C82659D7D75]    Script Date: 16/09/2024 13:35:36 ******/
ALTER TABLE [dbo].[USERS] ADD UNIQUE NONCLUSTERED 
(
	[AUTHENTICATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__USERS__E0B75F6F9FD86444]    Script Date: 16/09/2024 13:35:36 ******/
ALTER TABLE [dbo].[USERS] ADD UNIQUE NONCLUSTERED 
(
	[USER_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AUTHENTICATIONS]  WITH CHECK ADD  CONSTRAINT [FK_AUTHENTICATIONS_AUTHORIZATIONS] FOREIGN KEY([AUTHORIZATION_ID])
REFERENCES [dbo].[AUTHORIZATIONS] ([AUTHORIZATION_ID])
GO
ALTER TABLE [dbo].[AUTHENTICATIONS] CHECK CONSTRAINT [FK_AUTHENTICATIONS_AUTHORIZATIONS]
GO
ALTER TABLE [dbo].[USERS]  WITH CHECK ADD  CONSTRAINT [FK_USERS_AUTHENTICATIONS] FOREIGN KEY([AUTHENTICATION_ID])
REFERENCES [dbo].[AUTHENTICATIONS] ([AUTHENTICATION_ID])
GO
ALTER TABLE [dbo].[USERS] CHECK CONSTRAINT [FK_USERS_AUTHENTICATIONS]
GO
USE [master]
GO
ALTER DATABASE [TestDB] SET  READ_WRITE 
GO
